#!/bin/bash

LXC=/usr/bin/lxc
CONF="$CB_CONF/creator/resources/10_container_box.conf"

function create_container {
    $LXC launch ubuntu:bionic $1
    echo "Waiting for end of init"
    sleep 5
}

function install_de_xfce {
    $LXC exec $1 -- apt update
    $LXC exec $1 -- apt install -yq xubuntu-desktop
}

function install_de_kde {
    $LXC exec $1 -- apt update
    $LXC exec $1 -- apt install -yq kubuntu-desktop
}

function install_de_mate {
    $LXC exec $1 -- apt update
    $LXC exec $1 -- apt install -yq ubuntu-mate-desktop
}

function install_de_gnome {
    $LXC exec $1 -- apt update
    $LXC exec $1 -- apt install -yq ubuntu-desktop
}

function install_de {
    if [ "$2" = "XFCE" ]; then
        install_de_xfce $1
    fi
    if [ "$2" = "KDE" ]; then
        install_de_kde $1
    fi
    if [ "$2" = "MATE" ]; then
        install_de_mate $1
    fi
    if [ "$2" = "GNOME" ]; then
        install_de_gnome $1
    fi
}

function finish_install {
    $LXC exec $1 -- apt install -yq lightdm lightdm-gtk-greeter
    $LXC exec $1 -- apt install -yq sudo

    $LXC exec $1 -- mkdir /etc/lightdm/lightdm.conf.d/
    $LXC file push $CONF $1/etc/lightdm/lightdm.conf.d/
    $LXC exec $1 -- bash -c "echo 'greeter-session=lightdm-gtk-greeter' >> /etc/lightdm/lightdm.conf.d/10_container_box.conf"

}

create_container $1
install_de $1 $2
finish_install $1