#!/bin/bash

LXC=/usr/bin/lxc
CHOWN=/bin/chown
GREP=/bin/grep
CUT=/usr/bin/cut
LXC_USER=$($GREP "lxd" /etc/subuid | $CUT -d':' -f2)
NEWID=$(($LXC_USER + $1))


$CHOWN "$NEWID":"$NEWID" $3
$LXC config device add $2 wl0 disk source=$3 path=$4 