#!/bin/bash

CHROOT=""
XEPHYR=/usr/bin/Xephyr
XPRA=/usr/bin/xpra
LXC=/usr/bin/lxc
MKDIR=/bin/mkdir
CHMOD=/bin/chmod
CHOWN=/bin/chown
XORG=/usr/bin/Xorg
SUDO=/usr/bin/sudo
CUT=/usr/bin/cut
GREP=/bin/grep

function usage {
    echo "$1 --name(-n) NAME_OF_BOX --fullscreen(-f) yes|no --method(-m) xephyr|xpra|cli"
    echo "--name [-n]: Name of the box to launch"
    echo "--fullscreen [-f]: Launch fullscreen display"
    echo "--method [-m]: Share a xephyr display forward display via xpra or open a new terminal window"
    echo "--help [-h]: show this help"
}

function get_last_display {
    str1=$(ls /tmp/.X11-unix/ | tail -n1)
    str2=""

    echo "${str1/X/$str2}"
}

function create_xorg {
    echo $2
    $SUDO $XORG ":$2" $3 -noreset -terminate +extension GLX +extension RANDR +extension RENDER
	wait 
	# Remove the device once host is disconnected
	$LXC config device remove $1 "X$2"
}

function launch_xorg {
    last=$(get_last_display)
    display=$((last +1))

    create_xorg $1 $display &
    sleep 1

    # Ensure it is not already passed through
	$LXC config device remove $1 "X$display"
	$LXC config device add $1 "X$display" disk path="/tmp/.X11-unix/X0" source="/tmp/.X11-unix/X$display"

	echo "Display :$display socket passed to $1"
}

function create_xephyr {
    $CHROOT $XEPHYR ":$2" $3 -glamor -title "ContainerBox -- $1" -resizeable -br -terminate -noreset +extension GLX +extension RANDR +extension RENDER
	wait 
	# Remove the device once host is disconnected
	$LXC config device remove $1 "X$2"
}

function launch_xephyr {
    last=$(get_last_display)
    display=$((last +1))

    create_xephyr $1 $display &
    sleep 1

    # Ensure it is not already passed through
	$LXC config device remove $1 "X$display"
	$LXC config device add $1 "X$display" disk path="/tmp/.X11-unix/X0" source="/tmp/.X11-unix/X$display"

	echo "Display :$display socket passed to $1"
}

function launch_xephyr_fullscreen {
    last=$(get_last_display)
    display=$((last +1))

    create_xephyr $1 $display "-fullscreen" &
    sleep 1

    # Ensure it is not already passed through
	$LXC config device remove $1 "X$display"
	$LXC config device add $1 "X$display" disk path="/tmp/.X11-unix/X0" source="/tmp/.X11-unix/X$display"

	echo "Display :$display socket passed to $1"
}

function create_xpra {
    # Launch xpra server
    $LXC exec $1 -- xpra start-desktop --xvfb="Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./0.log -config /etc/xpra/xorg.conf :0" --bind-tcp=0.0.0.0:10000
    
    echo "Waiting for server creation"
    lxdip=$($LXC list | $GREP "| $1 " | $CUT -d'|' -f4 | $CUT -d' ' -f2)
    while [ -z "$(nmap $lxdip -p 10000 | $GREP open)" ]; do
        echo "still closed"
        sleep 1
    done

}

function launch_xpra {
    create_xpra $1
    lxdip=$($LXC list | $GREP "| $1 " | $CUT -d'|' -f4 | $CUT -d' ' -f2)
    xpra attach tcp/$lxdip:10000 --encoding=rgb --speed=100 &
}

function launch_xpra_fullscreen {
    create_xpra $1
    lxdip=$($LXC list | $GREP "| $1 " | $CUT -d'|' -f4 | $CUT -d' ' -f2)
    xpra attach tcp/$lxdip:10000 --encoding=rgb --speed=100 --desktop-fullscreen=True &
}

function start_lightdm {
    $LXC exec $1 -- lightdm
}

function launch_terminal {
    if [ -f "/usr/bin/gnome-terminal" ]; then
        /usr/bin/gnome-terminal -- /bin/bash -c "lxc exec $1 -- bash || sh"
    elif [ -f "/usr/bin/tilix" ]; then
        /usr/bin/tilix -e lxc exec $1 -- bash || sh
    elif [ -f "/usr/bin/konsole" ]; then
        /usr/bin/konsole -e lxc exec $1 -- bash || sh
    elif [ -f "/usr/bin/xterm" ]; then
        /usr/bin/xterm -e lxc exec $1 -- bash || sh
    else 
        echo "[ERROR]: cannot find a supported terminal emulator"
        echo "Possible options are gnome-terminal, tilix, konsole and xterm"
        echo "If you want the one you are using to be available, please feel free to open an issue"
    fi
}

function launch {
    # fullscreen
    if [ "$3" = "yes" ] && [ "$2" = "xephyr" ]; then
        launch_xephyr_fullscreen $1
    fi
    if [ "$3" = "yes" ] && [ "$2" = "xpra" ]; then
        launch_xpra_fullscreen $1
    fi
    if [ "$3" = "yes" ] && [ "$2" = "xorg" ]; then
        launch_xorg $1
    fi
    # Resizeable window
    if [ "$3" = "no" ] && [ "$2" = "xephyr" ]; then
        launch_xephyr $1
    fi
    if [ "$3" = "no" ] && [ "$2" = "xpra" ]; then
        launch_xpra $1
    fi
    if [ "$3" = "no" ] && [ "$2" = "xorg" ]; then
        launch_xorg $1
    fi

    if [ "$2" = "cli" ]; then
        launch_terminal $1
    else
        # launch lightdm
        start_lightdm $1
    fi
    if [ "$2" = "xpra" ]; then
        $LXC exec $1 -- killall Xorg
    fi
    

}

METHOD="xephyr"
FULLSCREEN="no"

CMD=$0

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -m|--method)
    METHOD="$2"
    if [ "$2" = "xephyr" ] || [ "$2" = "xpra" ] || [ "$2" = "xorg" ] || [ "$2" = "cli" ]; then
        METHOD="$2"
    else
        echo "Unknown value '$2' for parameter $key"
        exit
    fi
    shift # past argument
    shift # past value
    ;;
    -f|--fullscreen)
    if [ "$2" = "yes" ] || [ "$2" = "no" ]; then
        FULLSCREEN="$2"
    else
        echo "Unknown value '$2' for parameter $key"
        exit
    fi    
    shift # past argument
    shift # past value
    ;;
    -n|--name)
    NAME="$2"
    shift # past argument
    shift # past value
    ;;
    -h|--help)
    usage $CMD
    exit
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    usage $CMD
    exit
    ;;
esac
done

if [ -z $NAME ]; then
    echo "Provide at least the name of the box"
    exit 
fi

# Check if container exists
testing_life=$($LXC list | $GREP "| $NAME ")
if [ -z  "$testing_life" ]; then
    echo "$NAME does not exist !"
    exit
fi

# Start container if not running 
testing_life=$($LXC list | $GREP "| $NAME " | $GREP "RUNNING")
if [ -z "$testing_life" ]; then
    $LXC start $NAME
fi
testing_life=$($LXC list | $GREP "| $NAME " | $GREP "RUNNING")
if [ -z "$testing_life" ]; then
    echo "[ERROR] : Unable to start container"
    exit
fi

launch $NAME $METHOD $FULLSCREEN
