#!/bin/bash
LXC=/snap/bin/lxc
BASH=/bin/bash
GREP=/bin/grep
CB_CONF=/etc/ContainerBox

CONFIG_DIR="$CB_CONF/creator"

function usage {
    echo "ContainerBox create --template(-t) DISTRO_NAME --desktop_environment(-d) DE_NAME --name(-n) NAME_OF_BOX --xpra(-x) yes|no --user(-u) USERNAME --password(-p) PASSWORD"
    echo ""
    echo "--template [-t]: Ditribution template to use (debian, fedora[default], ubuntu or 'vanilla NAME_DISTRO')"
    echo "--desktop_environment [-d]: Desktop environment to install (MATE, XFCE[default], GNOME or KDE)"
    echo "--name [-n]: Name of the box to create"
    echo "--xpra [-x]: Install xpra support (yes or no)"
    echo "--user [-u]: Main user that will be created and granted admin access [default: 'main']"
    echo "--password [-p]: Password of the newly created user [default: random 16 char password]"
    echo "--help [-h]: show this help"
}

function generate_password {
   PWD=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-16};echo;)
   echo $PWD
}

function finish_setup {
    # Passthrough gpu device
    $LXC config device add $1 gpu gpu

    # Create the user and set it as a sudoer
    $LXC exec $1 -- groupadd sudo
    $LXC exec $1 -- groupadd wheel
    $LXC exec $1 -- useradd -m $2 -G sudo
    $LXC exec $1 -- usermod -a -G wheel $2

    # Change password
    $LXC exec $1 -- bash -c "echo -e \"$3\n$3\n\" | passwd $2"

    # Disable autostart by default
    $LXC config set $1 boot.autostart false

}

if [ "$1" = "help" ]; then
    usage $0
    exit
fi


XPRA='no'
TEMPLATE='fedora'
DE='XFCE'
USER='main'
PASSWORD=$(generate_password)


while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -t|--template)
    TEMPLATE="$2"
    shift # past argument
    shift # past value
    ;;
    -d|--desktop_environment)
    DE="$2"
    shift # past argument
    shift # past value
    ;;
    -n|--name)
    NAME="$2"
    shift # past argument
    shift # past value
    ;;
    -x|--xpra)
    if [ "$2" = "yes" ] || [ "$2" = "no" ]; then
        XPRA="$2"
    else
        echo "Unknown value '$2' for parameter $key"
        exit
    fi
    shift # past argument
    shift # past value
    ;;
    -u|--user)
    USER="$2"
    shift # past argument
    shift # past value
    ;;
    -p|--password)
    PASSWORD="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    echo "Unknown parameter '$key' !"
    exit
    ;;
esac
done

if [ -z $NAME ]; then
    echo "Provide at least the name of the box"
    exit 
fi

if [ ! -f "$CONFIG_DIR/templates/$TEMPLATE" ]; then 
    echo "Template '$TEMPLATE' does not exist. You can create it if you want and place the file in the '$(pwd)/$CONFIG_DIR' folder"
fi

if [ "$TEMPLATE" != "vanilla" ] && [ "$DE" != "XFCE" ] && [ "$DE" != "MATE" ] && [ "$DE" != "KDE" ] && [ "$DE" != "GNOME" ] && [ "$DE" != "none" ]; then
    echo "Desktop Environment $DE is not supported (yet?). You can contact me if you want it to be added."
    echo "In the meantime, you can set the Desktop Environment parameter to 'none' and install yours after"
    exit
fi

if [ "$XPRA" = "yes" ]; then
    if [ ! -f "$CONFIG_DIR/templates/xpra_$TEMPLATE" ]; then
        echo "XPRA is not possible for template $TEMPLATE"
        exit 
    fi
fi

echo "Creating Box $NAME"
echo "Using template '$TEMPLATE'"
echo "Installing Desktop Environment '$DE'"
echo "Setting $USER as the first user (and sudoer)"
echo "Password will be set to: $PASSWORD"
echo "Installing experimental Xpra support ? $XPRA"

if [ "$XPRA" = "yes" ]; then
    CB_CONF=$CB_CONF $BASH $CONFIG_DIR/templates/xpra_$TEMPLATE $NAME $DE
else
    CB_CONF=$CB_CONF $BASH $CONFIG_DIR/templates/$TEMPLATE $NAME $DE
fi

test=$($LXC list | $GREP " $NAME ")
if [ "$test" = *"$NAME"* ] ; then
    echo "[ERROR] : Failed to create container $NAME"
    exit
fi
finish_setup $NAME $USER $PASSWORD